default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task-p_development

test:
  <<: *default
  database: task-p_test

production:
  <<: *default
  database: task-p_production
  username: task-p
  password: <%= ENV['TASK-P_DATABASE_PASSWORD'] %>
